# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 00:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_live',
        ),
    ]
