# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_remove_course_is_live'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
        migrations.AddField(
            model_name='course',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
